mixed-port: 17890
allow-lan: false
bind-address: 127.0.0.1
mode: rule
log-level: info
ipv6: true
tcp-concurrent: true
unified-delay: true

proxies:
  - name: upstream-192.168.50.12
    type: http
    server: 192.168.50.12
    port: 7890

rule-providers:
  proxy-blacklist:
    type: http
    behavior: domain
    format: mrs
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/gfw.mrs
    path: ./ruleset/proxy-blacklist.mrs
    interval: 86400
    proxy: upstream-192.168.50.12

rules:
  - IP-CIDR,127.0.0.0/8,DIRECT,no-resolve
  - IP-CIDR,10.0.0.0/8,DIRECT,no-resolve
  - IP-CIDR,172.16.0.0/12,DIRECT,no-resolve
  - IP-CIDR,192.168.0.0/16,DIRECT,no-resolve
  - DOMAIN-SUFFIX,tode.ltd,DIRECT
  - DOMAIN-SUFFIX,feishu.cn,DIRECT
  - DOMAIN-SUFFIX,larksuite.com,DIRECT
  - RULE-SET,proxy-blacklist,upstream-192.168.50.12
  - MATCH,DIRECT
